version: '3.8'
services:
  # ZooKeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  # Hazelcast (force x86)
  hazelcast:
    image: hazelcast/hazelcast:5
    platform: linux/amd64
    ports: ["5701:5701"]

  # Inventory Service
  inventory-service:
    build: ./inventory-service
    ports: ["8081:8081"]
    volumes:
      - sqlite_data:/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/data/app.db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.sqlite.JDBC

  # Booking Service
  booking-service:
    build: ./booking-service
    depends_on: [kafka, hazelcast]
    ports: ["8082:8082"]
    volumes:
      - sqlite_data:/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlite:/data/app.db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.sqlite.JDBC
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      HAZELCAST_CLUSTER_MEMBERS: hazelcast

  # API Gateway
  api-gateway:
    build: ./api-gateway
    depends_on: [inventory-service, booking-service]
    ports: ["8080:8080"]

volumes:
  sqlite_data:
