version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB:       userdb
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED:     "true"
    ports:
      - "8080:8080"

volumes:
  db_data:
