server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: http://inventory-service:8081
          predicates:
            - Path=/inventory/**
        - id: booking
          uri: http://booking-service:8082
          predicates:
            - Path=/bookings/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
