server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://authentication:8080
          predicates:
            - Path=/auth/**
        - id: booking-service
          uri: http://booking-service:8082
          predicates:
            - Path=/booking/**
        - id: inventory-service
          uri: http://inventory-service:8081
          predicates:
            - Path=/inventory/**
        - id: payment-service
          uri: http://payment-service:8090
          predicates:
            - Path=/payment/**
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
