server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8085
          predicates:
            - Path=/auth/**
        - id: booking-service
          uri: http://booking-service:8082
          predicates:
            - Path=/bookings/**
        - id: inventory-service
          uri: http://inventory-service:8081
          predicates:
            - Path=/inventory/**
        - id: payment-service
          uri: http://payment-service:8090
          predicates:
            - Path=/payment/**
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    enabled: false
