# src/main/resources/application.yml
server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bookingdb
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    com.example.booking: DEBUG
