server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:/data/app.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect

  flyway:
    enabled: true
    locations: classpath:db/migration-inventory
    table: inventory_schema_history
    baseline-on-migrate: true
    clean-on-validation-error: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
