server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
